src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Carbon\Carbon;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column]
    private ?int $numberOfTasks = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): static
    {
        $this->filename = $filename;

        return $this;
    }

    public function getNumberOfTasks(): ?int
    {
        return $this->numberOfTasks;
    }

    public function setNumberOfTasks(int $numberOfTasks): static
    {
        $this->numberOfTasks = $numberOfTasks;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    #[ORM\PreUpdate]
    #[ORM\PrePersist]
    public function setUpdatedAt()
    {
        $this->updatedAt = new \DateTimeImmutable();

        return $this;
    }
    public function getUpdatedAtString(): ?string
    {
        if ($this->updatedAt instanceof \DateTimeInterface) {
            $carbonUpdatedAt = Carbon::instance($this->updatedAt);
            return $carbonUpdatedAt->diffForHumans();
        }

        return null;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control'],
            ])
            ->add('imageFile', FileType::class, [
                'label' => 'Project Image',
                'required' => false,
                'mapped' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('filename', TextType::class, [
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control'],
            ])
            ->add('numberOfTasks', TextType::class, [
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control'],
            ])
            ->add('description', TextType::class, [
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control'],
            ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'In Progress' => 'in_progress',
                    'Done' => 'done',
                    'Blocked' => 'blocked',
                ],
                'label' => 'Status',
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ProjectSearchType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/project')]
class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_project_index', methods: ['GET', 'POST'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {
        $form = $this->createForm(ProjectSearchType::class);
        $form->handleRequest($request);

        $filterData = $form->isSubmitted() ? $form->getData() : [];

        $projects = $entityManager
            ->getRepository(Project::class)
            ->findByFilter($filterData);

        // Paginate the results
        $projects = $paginator->paginate(
            $projects,
            $request->query->getInt('page', 1),
            8
        );

        return $this->render('project/index.html.twig', [
            'projects' => $projects,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/new', name: 'app_project_new', methods: ['GET', 'POST'])]
    #[Security("is_granted('ROLE_ADMIN')")]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->handleImageUpload($form, $project);
            $entityManager->persist($project);
            $entityManager->flush();

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_project_show', methods: ['GET'])]
    public function show(Project $project): Response
    {
        return $this->render('project/show.html.twig', [
            'project' => $project,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_project_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Project $project, EntityManagerInterface $entityManager, MailerInterface $mailer, UserRepository $userRepository): Response
    {
        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException('Access denied. You do not have the required role.');
        }
        $originalStatus = $project->getStatus(); // Store the original status before form submission

        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['imageFile']->getData();
            if ($file) {
                $this->handleImageUpload($form, $project);
            }
            $entityManager->flush();
            if ($originalStatus !== $project->getStatus()) {
                $users = $userRepository->findByRole('ROLE_ADMIN');
                $this->sendEmailAction($mailer, $users, $project);
            }
            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('project/edit.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_project_delete', methods: ['POST'])]
    public function delete(Request $request, Project $project, EntityManagerInterface $entityManager): Response
    {
        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException('Access denied. You do not have the required role.');
        }
        if ($this->isCsrfTokenValid('delete' . $project->getId(), $request->request->get('_token'))) {
            $entityManager->remove($project);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }
    private function handleImageUpload($form, $project): void
    {
        $imageFile = $form->get('imageFile')->getData();

        if ($imageFile) {
            $newFilename = md5(uniqid()) . '.' . $imageFile->guessExtension();

            try {
                $imageFile->move(
                    $this->getParameter('project_images_directory'),
                    $newFilename
                );
            } catch (FileException $e) {
                // Handle file upload error
            }

            $project->setImage($newFilename);
        }
    }
    private function sendEmailAction(MailerInterface $mailer, array $adminUsers, Project $project)
    {
        $email = (new Email())
            ->from('admin@example.com');

        foreach ($adminUsers as $adminUser) {
            $email->addTo($adminUser->getEmail());
        }

        $email
            ->subject('Project Status Change Notification')
            ->html(
                $this->renderView(
                    'emails/status_change_notification.html.twig',
                    ['project' => $project]
                )
            );

        $mailer->send($email);
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
	<button type="submit" class="btn btn-danger btn-lg">Delete</button>
</form>

templates/project/_edit_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{{ form_start(form) }}

	{{ form_row(form.title) }}
	{{ form_row(form.description) }}

	<div class="form-group">
		{{ form_label(form.imageFile, 'Project Image') }}
		{% if project.image %}
			<div id="image-preview-container">
				<img id="image-preview" src="{{ asset('uploads/projects/' ~ project.image) }}" alt="Existing Image" style="max-width: 200px; margin: 10px auto; cursor: pointer;" onclick="document.getElementById('project_imageFile').click();">
			</div>
		{% endif %}
		{{ form_widget(form.imageFile, { 'attr': { 'class': 'form-control', 'id': 'project_imageFile', 'style': 'display:none;' } }) }}
		{{ form_errors(form.imageFile) }}
	</div>
	{{ form_row(form.filename) }}
	{{ form_row(form.numberOfTasks) }}
	{{ form_row(form.status) }}
	{{form_widget(form._token)}}
	<div class="row justify-content-center mt-4">
		<div class="col-auto d-flex justify-content-between">
			<button type="submit" class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
			{{ form_end(form) }}
			{% if edit_mode %}
				{{ include('project/_delete_form.html.twig') }}
			{% endif %}
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
	<script>
		$(document).ready(function () {
$('#project_imageFile').change(function () {
readURL(this);
});

function readURL(input) {
if (input.files && input.files[0]) {
var reader = new FileReader();
reader.onload = function (e) {
$('#image-preview').attr('src', e.target.result);
};
reader.readAsDataURL(input.files[0]);
}
}
});
	</script>
{% endblock %}

templates/project/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}

<div class="row justify-content-center mt-4">
	<div class="col-auto">
		<button type="submit" class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
	</div>
</div>
{{ form_end(form) }}

templates/project/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		<link rel="stylesheet" href="{{ asset('css/easion.css') }}">
		<link href="https://fonts.googleapis.com/css?family=Nunito:400,600|Open+Sans:400,600,700" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" crossorigin="anonymous"/>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>
	<body>
		<div class="dash dash-compact">
			<div class="dash-nav dash-nav-dark">
				<header>
					<a class="menu-toggle">
						<i class="fas fa-bars"></i>
					</a>
					<a href="{{ path('app_project_index') }}" class="easion-logo">
						<span>Easion</span>
					</a>
				</header>
				<nav class="dash-nav-list">
					{% if is_granted('ROLE_ADMIN') %}
						<a href="{{ path('app_project_new') }}" class="dash-nav-item">
							<i class="fa-solid fa-plus"></i>
							Create new project
						</a>
					{% endif %}
				</nav>
			</div>
			<div class="dash-app">
				<header class="dash-toolbar">
					<a class="menu-toggle">
						<i class="fas fa-bars"></i>
					</a>
					<div class="tools">
						<div class="dropdown tools-item">
							<a href="#" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{% if app.user %}
									<img src="{{ asset('uploads/users/' ~ app.user.picture | default('default-profile-image.jpg')) }}" alt="User Image" class="rounded-circle user-image" style="width: 50px; height: 50px;">
								{% else %}
									<i class="fas fa-user"></i>
								{% endif %}
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
								{% if app.user %}
									<a class="dropdown-item" href="{{ path('app_user_edit') }}">Profile</a>
									<a class="dropdown-item" href="{{ path('app_logout') }}">Logout</a>
								{% endif %}
							</div>
						</div>
					</div>
				</header>
				<main class="dash-content">
					<div class="container-fluid"> {% block body %}{% endblock %}
						</div>

					</main>
				</div>
			</div>
		</body>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<script src="{{ asset('js/easion.js') }}"></script>
	</html>

templates/project/edit.html.twig
{% extends 'project/base.html.twig' %}

{% block title %}
	Edit Project
{% endblock %}

{% block body %}
	<div class="container">
		<div class="card bg-light">
			<article class="card-body">
				<h4 class="card-title mt-3 text-center">Edit Project</h4>
				{{ include('project/_edit_form.html.twig', {button_label: 'Update', edit_mode: true}) }}
			</article>
		</div>
	</div>
{% endblock %}

templates/project/index.html.twig
{% extends 'project/base.html.twig' %}

{% block title %}
	Project index
{% endblock %}


{% block body %}

	{{ form_start(form, {'attr': {'class': 'mb-4'}}) }}

	<div class="row">
		<div class="col-md-3 form-group">
			{{ form_label(form.title, 'Project Name', {'label_attr': {'class': 'sr-only'}}) }}
			{{ form_widget(form.title, {'attr': {'class': 'form-control', 'placeholder': 'Project Name'}}) }}
		</div>

		<div class="col-md-3 form-group">
			{{ form_label(form.status, 'Status' , {'label_attr': {'class': 'sr-only'}}) }}
			{{ form_widget(form.status, {'attr': {'class': 'form-control'}}) }}
		</div>

		<div class="col-md-5 form-group">
			{{ form_label(form.filename, 'Filename', {'label_attr': {'class': 'sr-only'}}) }}
			{{ form_widget(form.filename, {'attr': {'class': 'form-control', 'placeholder': 'Filename'}}) }}
		</div>

		<div class="col-md form-group">
			<button type="submit" class="btn btn-dark">
				<i class="fa fa-filter" aria-hidden="true"></i>
			</button>
		</div>
	</div>

	{{ form_end(form) }}


	<div class="row">
		{% for project in projects %}
			<div class="col-md-3 mb-4">
				<div class="card text-center">
					<img src="{{ asset('uploads/projects/' ~ project.image) }}" class="card-img-top" alt="{{ project.title }}" style="max-height: 150px;"/>
					<div class="card-body">
						<h5 class="card-title">{{ project.title }}</h5>
						<p class="card-text">{{ project.description }}</p>
						{% if is_granted('ROLE_ADMIN') %}
							<a href="{{ path('app_project_edit', { id: project.id }) }}" class="btn btn-outline-light text-dark" style="border-color: black;">
								<i class="fa fa-suitcase" aria-hidden="true" style="color: red;"></i>
								<span class="ml-2">Edit Project</span>
							</a>
						{% endif %}
					</div>
					<div class="card-footer text-muted small d-flex justify-content-between">
						<div>last updated
							{{ project.updatedAtString }}</div>
						<div>{{ project.numberOfTasks }}
							tasks</div>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-12">
				<p>No records found.</p>
			</div>
		{% endfor %}
		{{ knp_pagination_render(projects, 'pagination.html.twig') }}
	</div>
{% endblock %}

templates/project/new.html.twig
{% extends 'project/base.html.twig' %}

{% block title %}New Project
{% endblock %}

{% block body %}
	<div class="container">
		<div class="card bg-light">
			<article class="card-body">
				<h4 class="card-title mt-3 text-center">Create Project</h4>

				{{ include('project/_form.html.twig') }}
			</article>
		</div>
	</div>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project{% endblock %}

{% block body %}
    <h1>Project</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ project.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ project.title }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ project.image }}</td>
            </tr>
            <tr>
                <th>Filename</th>
                <td>{{ project.filename }}</td>
            </tr>
            <tr>
                <th>NumberOfTasks</th>
                <td>{{ project.numberOfTasks }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ project.description }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ project.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_project_index') }}">back to list</a>

    <a href="{{ path('app_project_edit', {'id': project.id}) }}">edit</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}